#数据库的连接信息
spring:
  application:
    name: tlias-web-mangement
  # 数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  #文件上传大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB

# Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    #驼峰喵喵
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTemplate: debug

#阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: itheima--web-ai
    region: cn-beijing